version: '3.8'
services:
  php:
    build:
      args:
        user: www
        uid: 1000
      context: .docker/
      dockerfile: Dockerfile
    container_name: oop_php
    volumes:
      - ./:/var/www/html
      - .docker/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - redis
      - mariadb
    networks:
      - app-network

  redis:
    image: redis
    container_name: oop_redis
    command: redis-server /etc/redis/redis.conf
    volumes:
      - .docker/redis.conf:/etc/redis/redis.conf
      - .docker/redis/redis_data:/data
    networks:
      - app-network

  nginx:
    image: nginx
    container_name: oop_nginx
    volumes:
      - .docker/nginx.conf:/etc/nginx/nginx.conf
      - ./:/var/www/html
    ports:
      - 80:80
      - 443:443
    depends_on:
      - php
    networks:
      - app-network

  mariadb:
    image: mariadb
    container_name: oop_mariadb
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - .docker/mariadb/db:/var/lib/mysql # Монтирование тома для хранения данных MariaDB
      - .docker/mariadb/my.cnf:/etc/mysql/my.cnf # Монтирование файла конфигурации my.cnf

    networks:
      - app-network

networks:
  app-network: